package aoc.solutions.day7;

import java.util.Arrays;
import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Optional;
import java.util.Set;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import static java.lang.Math.toIntExact;
import static java.util.Arrays.stream;
import static java.util.Collections.singletonList;

/**
 *
 * @author in-rahul.khandelwal
 */
public class Solution {

    public static void main(String[] args) {
        part2_canContain();
    }

    private static void part1_possibleContainers() {
        System.out.println(findBagContaining(new Bag(1, "shiny gold"), new HashSet<>()).size() - 1);
    }

    private static Set<String> findBagContaining(Bag bag, Set<String> visitedColors) {
        visitedColors.add(bag.item);
        OuterBag[] possibleTrades = getBagsContaining(bag);
        stream(possibleTrades).forEach(t -> findBagContaining(t.input, visitedColors));
        return visitedColors;
    }

    private static OuterBag[] getBagsContaining(Bag i) {
        return input().filter(e -> stream(e.output).anyMatch(t -> t.item.equals(i.item) && t.amount >= i.amount)).toArray(OuterBag[]::new);
    }

    private static void part2_canContain() {
        System.out.println(findNumberOfBags(new LinkedList<>(singletonList(new Bag(1, "shiny gold")))) - 1);
    }

    private static long findNumberOfBags(Deque<Bag> remaining) {
        long total = 0;
        while (!remaining.isEmpty()) {
            total += findBagsInside(remaining, remaining.pop());
        }
        return total;
    }

    private static long findBagsInside(Deque<Bag> remaining, Bag current) {
        Optional<OuterBag> fuelTrade = getOuterBagItem(current);
        fuelTrade.ifPresent(outerBag -> stream(outerBag.output)
                .flatMap(i -> IntStream.rangeClosed(1, toIntExact(i.amount))
                        .mapToObj(e -> new Bag(1, i.item))).forEach(remaining::add));
        return current.amount;
    }

    private static Optional<OuterBag> getOuterBagItem(Bag i) {
        return input().filter(e -> e.input.item.equals(i.item)).findAny();
    }

    private static Stream<OuterBag> input() {
        String inputStr = "light chartreuse bags contain 1 mirrored yellow bag, 2 vibrant violet bags.\n"
                + "dotted silver bags contain 2 dotted orange bags, 3 bright fuchsia bags, 5 bright tomato bags, 3 faded turquoise bags.\n"
                + "plaid indigo bags contain 1 pale violet bag, 4 mirrored violet bags.\n"
                + "faded turquoise bags contain 5 faded lavender bags.\n"
                + "striped yellow bags contain 5 vibrant black bags, 1 mirrored gold bag.\n"
                + "dull tan bags contain 1 vibrant aqua bag.\n"
                + "striped brown bags contain 1 vibrant orange bag, 1 posh bronze bag, 4 dim purple bags.\n"
                + "bright teal bags contain 3 muted cyan bags, 2 drab white bags, 1 drab gray bag.\n"
                + "wavy tan bags contain 4 wavy tomato bags, 1 dim tan bag.\n"
                + "light lavender bags contain 1 dotted black bag, 1 wavy maroon bag, 5 pale white bags, 1 clear tan bag.\n"
                + "dull orange bags contain 5 bright brown bags, 1 muted gold bag, 4 vibrant black bags, 4 posh bronze bags.\n"
                + "posh cyan bags contain 2 mirrored tomato bags, 5 light salmon bags, 1 faded brown bag, 4 vibrant red bags.\n"
                + "dark lavender bags contain 2 faded purple bags.\n"
                + "dark white bags contain 5 muted green bags.\n"
                + "striped olive bags contain 1 muted chartreuse bag.\n"
                + "bright crimson bags contain 3 drab salmon bags, 1 faded plum bag, 4 shiny brown bags, 5 pale orange bags.\n"
                + "dark tomato bags contain 5 dim aqua bags.\n"
                + "light olive bags contain 2 drab blue bags, 1 plaid purple bag.\n"
                + "muted gray bags contain 1 mirrored plum bag.\n"
                + "bright salmon bags contain 3 striped plum bags, 1 dull silver bag, 4 striped indigo bags, 4 striped cyan bags.\n"
                + "wavy gold bags contain 3 drab tomato bags, 5 pale gold bags, 1 plaid tan bag, 5 vibrant gold bags.\n"
                + "muted fuchsia bags contain 3 vibrant plum bags, 1 clear chartreuse bag, 1 pale white bag.\n"
                + "light purple bags contain 5 vibrant olive bags, 4 bright maroon bags, 3 posh tomato bags.\n"
                + "vibrant gray bags contain 5 shiny silver bags.\n"
                + "vibrant beige bags contain 2 pale crimson bags, 5 pale olive bags, 4 posh yellow bags, 3 dotted orange bags.\n"
                + "drab beige bags contain 3 faded gold bags, 5 mirrored fuchsia bags.\n"
                + "light white bags contain 1 vibrant fuchsia bag, 3 posh tomato bags, 4 muted chartreuse bags.\n"
                + "posh lavender bags contain 3 dim fuchsia bags, 2 light violet bags, 3 wavy aqua bags, 5 vibrant lime bags.\n"
                + "vibrant fuchsia bags contain 2 wavy tomato bags, 3 plaid purple bags.\n"
                + "bright fuchsia bags contain 1 faded tomato bag, 4 bright salmon bags, 2 bright red bags.\n"
                + "dim bronze bags contain 5 drab blue bags.\n"
                + "wavy brown bags contain 3 dotted crimson bags.\n"
                + "striped plum bags contain 1 bright tomato bag.\n"
                + "posh coral bags contain 1 mirrored gray bag, 1 posh silver bag.\n"
                + "wavy teal bags contain 5 dark bronze bags.\n"
                + "posh crimson bags contain 3 bright tomato bags, 3 wavy violet bags, 1 striped olive bag.\n"
                + "dark beige bags contain 2 drab turquoise bags.\n"
                + "dull green bags contain 2 vibrant purple bags, 5 dark red bags.\n"
                + "wavy violet bags contain 5 faded lavender bags, 2 faded turquoise bags, 4 shiny brown bags.\n"
                + "wavy crimson bags contain 3 muted lavender bags.\n"
                + "light maroon bags contain 1 bright magenta bag, 5 dim yellow bags, 1 faded violet bag.\n"
                + "muted white bags contain 4 muted purple bags, 2 plaid gray bags, 2 vibrant maroon bags.\n"
                + "striped silver bags contain 4 shiny red bags, 5 vibrant coral bags.\n"
                + "clear chartreuse bags contain 3 pale gold bags.\n"
                + "posh silver bags contain 3 vibrant aqua bags, 5 muted coral bags, 4 drab crimson bags, 4 clear tan bags.\n"
                + "plaid green bags contain 1 striped lavender bag, 2 dim fuchsia bags, 5 vibrant black bags.\n"
                + "muted turquoise bags contain 3 faded green bags, 1 striped silver bag.\n"
                + "faded blue bags contain 3 pale crimson bags.\n"
                + "dull magenta bags contain 2 striped brown bags, 4 posh black bags, 4 dark teal bags.\n"
                + "dotted white bags contain 3 dotted magenta bags, 2 bright lavender bags, 5 drab crimson bags, 5 drab silver bags.\n"
                + "shiny orange bags contain 4 pale violet bags.\n"
                + "vibrant blue bags contain 2 clear yellow bags, 1 muted beige bag.\n"
                + "dull blue bags contain 3 pale violet bags, 3 dotted orange bags.\n"
                + "bright olive bags contain 4 dotted teal bags, 3 dotted violet bags.\n"
                + "faded gray bags contain 3 bright maroon bags, 2 shiny crimson bags, 2 plaid lavender bags.\n"
                + "clear tomato bags contain 1 vibrant white bag, 4 bright gold bags, 3 vibrant chartreuse bags, 1 posh violet bag.\n"
                + "bright indigo bags contain 3 wavy gold bags, 1 vibrant indigo bag, 1 mirrored chartreuse bag.\n"
                + "clear indigo bags contain 1 plaid gray bag, 3 faded gold bags, 2 clear beige bags.\n"
                + "dotted crimson bags contain 2 pale gold bags, 2 vibrant salmon bags, 5 posh maroon bags.\n"
                + "drab red bags contain 3 vibrant chartreuse bags, 5 wavy beige bags, 2 pale olive bags, 2 clear white bags.\n"
                + "clear black bags contain 3 faded chartreuse bags, 2 striped brown bags, 4 wavy crimson bags, 3 pale tomato bags.\n"
                + "shiny bronze bags contain 4 dark tan bags.\n"
                + "posh indigo bags contain 1 clear plum bag, 2 dotted red bags, 1 dull crimson bag, 4 dotted bronze bags.\n"
                + "dark cyan bags contain 3 plaid tan bags, 5 dim bronze bags.\n"
                + "shiny chartreuse bags contain 4 dark tomato bags, 2 striped salmon bags.\n"
                + "dim brown bags contain 1 pale olive bag, 4 posh tomato bags.\n"
                + "faded green bags contain 2 drab violet bags, 5 vibrant gray bags.\n"
                + "dull salmon bags contain 5 muted coral bags, 2 muted brown bags, 2 striped coral bags, 5 dark white bags.\n"
                + "wavy white bags contain 5 muted lime bags, 5 striped purple bags.\n"
                + "dim aqua bags contain 2 striped beige bags, 3 striped silver bags, 1 bright cyan bag, 5 clear blue bags.\n"
                + "dim salmon bags contain 5 mirrored lime bags, 1 vibrant plum bag, 5 mirrored fuchsia bags, 1 shiny gold bag.\n"
                + "dotted fuchsia bags contain 4 striped indigo bags, 4 wavy coral bags.\n"
                + "faded tan bags contain 5 dotted gold bags.\n"
                + "drab white bags contain 3 posh violet bags.\n"
                + "muted teal bags contain 4 dotted purple bags, 5 dark maroon bags, 3 dotted magenta bags, 1 pale beige bag.\n"
                + "dark magenta bags contain 3 posh red bags.\n"
                + "shiny cyan bags contain 3 dull red bags, 1 light coral bag.\n"
                + "plaid blue bags contain 3 shiny gold bags, 3 dull salmon bags, 4 vibrant silver bags, 4 light salmon bags.\n"
                + "dim orange bags contain 5 vibrant salmon bags, 2 dotted teal bags.\n"
                + "vibrant bronze bags contain 5 striped blue bags, 2 clear magenta bags.\n"
                + "faded olive bags contain 2 muted beige bags, 3 wavy beige bags.\n"
                + "dotted lime bags contain 2 mirrored tan bags.\n"
                + "dark silver bags contain 5 vibrant plum bags, 4 shiny gold bags, 3 light crimson bags, 2 dark cyan bags.\n"
                + "mirrored orange bags contain 5 shiny blue bags, 4 faded olive bags, 3 posh gold bags.\n"
                + "clear magenta bags contain 4 pale olive bags.\n"
                + "wavy blue bags contain 4 light gray bags.\n"
                + "pale maroon bags contain 1 dim aqua bag, 3 dotted fuchsia bags, 1 clear brown bag, 1 drab turquoise bag.\n"
                + "muted purple bags contain no other bags.\n"
                + "vibrant plum bags contain 5 wavy beige bags.\n"
                + "mirrored gray bags contain 3 dull plum bags, 5 pale blue bags.\n"
                + "striped lavender bags contain 3 wavy tomato bags, 1 striped tan bag, 5 posh silver bags.\n"
                + "dark violet bags contain 1 muted olive bag, 3 drab crimson bags.\n"
                + "bright tomato bags contain 4 pale violet bags.\n"
                + "posh white bags contain 5 clear white bags, 2 striped plum bags, 1 drab crimson bag, 5 wavy beige bags.\n"
                + "striped bronze bags contain 3 shiny teal bags, 5 bright lavender bags, 5 dark beige bags.\n"
                + "clear beige bags contain 2 mirrored magenta bags, 4 muted olive bags, 4 mirrored violet bags.\n"
                + "striped teal bags contain 5 mirrored cyan bags, 3 posh crimson bags, 4 vibrant tan bags.\n"
                + "bright blue bags contain 2 faded indigo bags, 4 wavy green bags.\n"
                + "striped orange bags contain 4 vibrant coral bags, 5 faded lavender bags, 2 vibrant maroon bags, 2 plaid cyan bags.\n"
                + "dim yellow bags contain 5 pale violet bags, 4 muted plum bags, 5 pale coral bags, 4 pale yellow bags.\n"
                + "dark bronze bags contain 5 posh gray bags.\n"
                + "wavy purple bags contain 5 faded tomato bags, 4 striped green bags, 1 striped tan bag, 5 dotted fuchsia bags.\n"
                + "light fuchsia bags contain 5 shiny lime bags, 1 dotted teal bag, 2 muted brown bags.\n"
                + "muted orange bags contain 3 striped chartreuse bags, 4 dim salmon bags, 2 pale indigo bags.\n"
                + "dotted green bags contain 5 dotted maroon bags, 4 vibrant beige bags, 3 striped beige bags.\n"
                + "wavy gray bags contain 2 mirrored fuchsia bags, 2 mirrored chartreuse bags, 3 mirrored blue bags.\n"
                + "dotted yellow bags contain 4 light tomato bags, 3 dull indigo bags.\n"
                + "light aqua bags contain 2 shiny brown bags, 2 bright coral bags.\n"
                + "muted cyan bags contain 5 faded olive bags, 5 pale white bags, 4 plaid tan bags.\n"
                + "pale tan bags contain 4 bright cyan bags.\n"
                + "vibrant magenta bags contain 3 light magenta bags.\n"
                + "light turquoise bags contain 3 dim bronze bags, 3 faded olive bags, 1 light orange bag, 2 shiny green bags.\n"
                + "light bronze bags contain 2 vibrant black bags, 2 clear indigo bags.\n"
                + "vibrant purple bags contain 3 bright red bags, 3 vibrant violet bags.\n"
                + "vibrant red bags contain 4 mirrored fuchsia bags, 1 drab tomato bag.\n"
                + "mirrored crimson bags contain 1 posh purple bag, 3 dotted magenta bags.\n"
                + "wavy olive bags contain 3 dark fuchsia bags.\n"
                + "pale beige bags contain 5 striped coral bags, 1 shiny violet bag.\n"
                + "posh teal bags contain 5 dull violet bags, 2 drab gold bags, 5 muted chartreuse bags, 1 drab turquoise bag.\n"
                + "faded tomato bags contain 5 mirrored salmon bags, 3 wavy coral bags.\n"
                + "muted salmon bags contain 4 vibrant gray bags.\n"
                + "dim lavender bags contain 4 clear lavender bags, 5 dotted coral bags.\n"
                + "shiny yellow bags contain 3 dim purple bags.\n"
                + "light tan bags contain 5 vibrant plum bags, 3 dim tomato bags.\n"
                + "shiny violet bags contain 1 mirrored salmon bag.\n"
                + "drab black bags contain 2 dark coral bags, 1 muted beige bag, 5 plaid orange bags, 1 dark tan bag.\n"
                + "wavy bronze bags contain 3 wavy lime bags, 3 striped white bags, 1 drab gray bag, 1 light orange bag.\n"
                + "bright green bags contain 1 vibrant gold bag, 2 vibrant tomato bags, 2 dim teal bags.\n"
                + "striped gold bags contain 5 striped purple bags, 1 faded purple bag, 2 dark beige bags, 1 mirrored silver bag.\n"
                + "wavy green bags contain 4 mirrored tan bags, 3 muted cyan bags, 4 plaid turquoise bags, 4 drab gray bags.\n"
                + "striped salmon bags contain 3 light yellow bags.\n"
                + "bright orange bags contain 2 shiny orange bags.\n"
                + "mirrored white bags contain 1 clear fuchsia bag.\n"
                + "striped coral bags contain no other bags.\n"
                + "light magenta bags contain 4 faded gold bags, 1 drab lime bag.\n"
                + "dull tomato bags contain 4 pale indigo bags, 4 pale white bags, 5 wavy silver bags, 3 faded indigo bags.\n"
                + "light black bags contain 5 dark lavender bags, 3 light blue bags, 3 dull turquoise bags.\n"
                + "posh fuchsia bags contain 1 wavy gold bag, 1 vibrant plum bag, 3 posh white bags.\n"
                + "shiny indigo bags contain 3 posh plum bags, 2 pale lime bags, 5 muted blue bags, 4 clear tan bags.\n"
                + "mirrored blue bags contain 3 dark indigo bags, 1 vibrant coral bag, 4 mirrored salmon bags.\n"
                + "pale tomato bags contain 3 plaid purple bags, 1 wavy violet bag.\n"
                + "dull silver bags contain 4 striped beige bags, 2 shiny lime bags, 1 muted olive bag, 5 dull blue bags.\n"
                + "mirrored silver bags contain 2 wavy coral bags, 3 dark lavender bags, 3 dull violet bags.\n"
                + "drab turquoise bags contain 2 dim purple bags, 5 clear white bags, 4 dull brown bags.\n"
                + "drab violet bags contain 1 pale white bag, 1 bright cyan bag.\n"
                + "pale indigo bags contain 4 striped blue bags, 1 plaid turquoise bag, 4 striped beige bags.\n"
                + "shiny fuchsia bags contain 1 striped olive bag, 1 vibrant orange bag, 2 striped indigo bags, 4 vibrant lime bags.\n"
                + "bright maroon bags contain 3 clear chartreuse bags.\n"
                + "shiny tomato bags contain 5 pale gold bags, 5 plaid gold bags, 2 dark white bags.\n"
                + "dotted olive bags contain 4 vibrant silver bags, 1 posh crimson bag.\n"
                + "drab teal bags contain 1 faded indigo bag.\n"
                + "muted plum bags contain 5 mirrored gray bags, 1 wavy maroon bag, 1 mirrored tomato bag, 3 drab crimson bags.\n"
                + "muted violet bags contain 5 drab crimson bags.\n"
                + "dark brown bags contain 1 shiny violet bag, 5 bright coral bags, 4 vibrant plum bags, 3 plaid silver bags.\n"
                + "posh purple bags contain 3 dull silver bags, 2 posh salmon bags, 5 dull chartreuse bags.\n"
                + "light yellow bags contain 5 striped olive bags, 2 mirrored tomato bags, 2 wavy plum bags.\n"
                + "bright silver bags contain 4 pale bronze bags, 2 drab turquoise bags, 2 striped coral bags.\n"
                + "dotted indigo bags contain 2 mirrored brown bags, 5 dim teal bags.\n"
                + "bright lavender bags contain 3 dark indigo bags, 4 wavy brown bags, 3 dotted tomato bags, 5 plaid beige bags.\n"
                + "drab purple bags contain 5 mirrored bronze bags.\n"
                + "clear olive bags contain 3 wavy red bags, 4 muted bronze bags, 2 dotted chartreuse bags.\n"
                + "mirrored coral bags contain 4 shiny salmon bags, 1 light orange bag, 4 faded yellow bags, 5 shiny maroon bags.\n"
                + "clear fuchsia bags contain 4 pale blue bags, 2 light lavender bags, 4 clear blue bags, 2 posh maroon bags.\n"
                + "drab fuchsia bags contain 4 drab bronze bags, 2 shiny bronze bags.\n"
                + "pale blue bags contain 2 dim purple bags, 3 plaid purple bags, 4 vibrant coral bags.\n"
                + "clear violet bags contain 1 muted chartreuse bag.\n"
                + "clear brown bags contain 3 faded chartreuse bags, 5 dotted plum bags, 2 mirrored plum bags, 4 plaid red bags.\n"
                + "muted maroon bags contain 1 muted chartreuse bag, 4 striped silver bags, 1 posh yellow bag, 4 dark indigo bags.\n"
                + "dim olive bags contain 5 clear beige bags, 5 pale blue bags.\n"
                + "bright violet bags contain 3 shiny salmon bags, 2 dull teal bags, 4 shiny blue bags, 2 posh teal bags.\n"
                + "drab green bags contain 5 wavy aqua bags, 5 dark lavender bags, 1 dull tan bag.\n"
                + "dim turquoise bags contain 2 dark brown bags, 3 dotted crimson bags, 3 dull salmon bags.\n"
                + "vibrant teal bags contain 2 dotted coral bags, 5 dim white bags.\n"
                + "posh maroon bags contain 3 muted purple bags, 2 bright tomato bags.\n"
                + "faded aqua bags contain 4 posh white bags, 2 mirrored violet bags.\n"
                + "vibrant violet bags contain 2 vibrant crimson bags, 2 drab crimson bags.\n"
                + "dotted salmon bags contain 3 faded violet bags, 4 clear beige bags, 2 bright coral bags.\n"
                + "dull chartreuse bags contain 1 dotted fuchsia bag, 5 posh black bags, 4 bright green bags.\n"
                + "vibrant orange bags contain 1 shiny green bag, 5 dull blue bags.\n"
                + "mirrored indigo bags contain 2 dull beige bags.\n"
                + "drab lavender bags contain 3 striped lime bags.\n"
                + "bright gold bags contain 5 posh silver bags.\n"
                + "dull fuchsia bags contain 2 striped tomato bags.\n"
                + "light lime bags contain 3 striped orange bags.\n"
                + "wavy magenta bags contain 3 clear fuchsia bags, 4 muted brown bags, 3 plaid lavender bags, 4 clear green bags.\n"
                + "faded beige bags contain 2 mirrored plum bags, 2 light blue bags, 4 dim purple bags, 5 plaid violet bags.\n"
                + "dark plum bags contain 2 shiny red bags, 5 shiny blue bags, 2 striped blue bags, 4 drab gray bags.\n"
                + "wavy turquoise bags contain 1 dim turquoise bag, 5 striped lavender bags, 3 drab aqua bags.\n"
                + "shiny white bags contain 4 shiny violet bags, 1 muted bronze bag, 3 clear tomato bags.\n"
                + "plaid yellow bags contain 4 vibrant indigo bags, 2 light gray bags.\n"
                + "dim crimson bags contain 5 dim brown bags, 3 dim white bags, 1 vibrant silver bag, 3 drab teal bags.\n"
                + "dim tomato bags contain 4 dull silver bags, 5 light gray bags.\n"
                + "wavy cyan bags contain 5 dark chartreuse bags, 1 dark maroon bag, 4 mirrored brown bags, 5 dotted fuchsia bags.\n"
                + "dim green bags contain 5 striped lime bags, 4 bright gold bags, 2 vibrant violet bags, 2 muted beige bags.\n"
                + "striped maroon bags contain 1 mirrored plum bag, 1 drab lavender bag, 5 posh teal bags.\n"
                + "dotted gray bags contain 3 vibrant white bags, 1 pale violet bag.\n"
                + "dotted beige bags contain 2 drab aqua bags.\n"
                + "clear crimson bags contain 2 dim white bags, 2 faded magenta bags, 1 dim tomato bag.\n"
                + "pale olive bags contain 2 posh tomato bags.\n"
                + "posh orange bags contain 3 muted cyan bags, 4 faded turquoise bags.\n"
                + "posh yellow bags contain 2 dotted orange bags, 2 striped crimson bags.\n"
                + "striped black bags contain 5 dark black bags, 2 faded magenta bags, 3 pale lavender bags.\n"
                + "faded orange bags contain 4 bright bronze bags.\n"
                + "pale turquoise bags contain 1 posh maroon bag, 4 faded violet bags, 2 faded lavender bags, 1 vibrant lime bag.\n"
                + "clear gray bags contain 4 posh gray bags, 4 shiny silver bags, 3 vibrant purple bags, 3 faded lavender bags.\n"
                + "shiny olive bags contain 4 vibrant lime bags, 5 faded coral bags.\n"
                + "vibrant maroon bags contain 5 light gray bags.\n"
                + "drab silver bags contain 3 vibrant salmon bags, 5 clear tan bags, 2 light white bags.\n"
                + "posh turquoise bags contain 5 plaid green bags, 2 light bronze bags, 4 shiny turquoise bags, 5 clear gray bags.\n"
                + "mirrored cyan bags contain 3 clear white bags.\n"
                + "shiny silver bags contain 4 vibrant coral bags.\n"
                + "clear plum bags contain 5 muted lavender bags, 5 striped coral bags.\n"
                + "dark crimson bags contain 4 posh violet bags.\n"
                + "muted red bags contain 1 dim maroon bag, 1 bright fuchsia bag, 3 dotted green bags, 3 striped gold bags.\n"
                + "clear lime bags contain 3 plaid cyan bags, 4 dim gray bags, 1 muted violet bag.\n"
                + "faded purple bags contain 3 muted beige bags, 1 posh white bag, 5 drab turquoise bags.\n"
                + "mirrored yellow bags contain 2 striped tan bags.\n"
                + "dim gray bags contain 3 bright green bags, 2 muted black bags, 5 mirrored maroon bags, 3 mirrored violet bags.\n"
                + "mirrored tomato bags contain 5 muted olive bags, 2 mirrored lime bags.\n"
                + "faded coral bags contain 3 bright brown bags, 4 vibrant purple bags, 3 posh coral bags.\n"
                + "wavy fuchsia bags contain 4 dim salmon bags, 4 vibrant violet bags, 5 muted beige bags, 2 dotted black bags.\n"
                + "light plum bags contain 1 wavy black bag.\n"
                + "dark tan bags contain 5 wavy green bags, 4 faded turquoise bags, 2 dark bronze bags, 3 light violet bags.\n"
                + "wavy beige bags contain no other bags.\n"
                + "dotted aqua bags contain 1 mirrored turquoise bag, 4 clear blue bags, 1 dotted teal bag, 3 bright bronze bags.\n"
                + "clear tan bags contain 3 clear gold bags, 3 plaid purple bags, 1 striped indigo bag, 5 bright tomato bags.\n"
                + "dark red bags contain 3 vibrant maroon bags, 3 vibrant fuchsia bags, 4 pale lavender bags, 4 dim purple bags.\n"
                + "dim violet bags contain 1 drab tomato bag, 2 vibrant white bags, 3 faded lavender bags.\n"
                + "dull gray bags contain 3 vibrant black bags.\n"
                + "mirrored aqua bags contain 4 clear fuchsia bags, 1 muted chartreuse bag.\n"
                + "pale violet bags contain no other bags.\n"
                + "faded silver bags contain 1 mirrored lime bag, 5 muted beige bags, 3 mirrored black bags, 1 clear gold bag.\n"
                + "posh tomato bags contain 3 dim purple bags, 1 vibrant maroon bag.\n"
                + "mirrored bronze bags contain 3 mirrored gold bags, 4 faded purple bags, 1 plaid cyan bag, 5 faded gold bags.\n"
                + "light red bags contain 3 muted black bags.\n"
                + "wavy salmon bags contain 1 light white bag, 1 clear white bag, 4 dark maroon bags.\n"
                + "posh lime bags contain 2 drab gold bags.\n"
                + "wavy chartreuse bags contain 4 muted teal bags, 3 plaid salmon bags.\n"
                + "dotted tomato bags contain 2 striped white bags, 4 dark lavender bags.\n"
                + "vibrant crimson bags contain no other bags.\n"
                + "posh violet bags contain 1 shiny lavender bag, 2 striped coral bags, 2 mirrored tan bags.\n"
                + "shiny lime bags contain 5 mirrored lime bags, 1 drab blue bag.\n"
                + "dotted magenta bags contain 5 bright salmon bags.\n"
                + "pale white bags contain 1 faded olive bag, 5 vibrant tomato bags.\n"
                + "muted lime bags contain 3 muted aqua bags.\n"
                + "dotted lavender bags contain 2 dim chartreuse bags, 2 vibrant olive bags.\n"
                + "faded crimson bags contain 4 bright plum bags, 5 dotted cyan bags.\n"
                + "drab tan bags contain 1 dim orange bag, 2 light teal bags, 2 light indigo bags.\n"
                + "pale black bags contain 2 posh silver bags.\n"
                + "dark orange bags contain 3 muted black bags, 2 pale violet bags, 4 faded cyan bags.\n"
                + "mirrored violet bags contain 1 faded olive bag, 3 vibrant crimson bags.\n"
                + "posh plum bags contain 3 vibrant maroon bags.\n"
                + "clear turquoise bags contain 1 dim purple bag.\n"
                + "plaid gray bags contain 1 dotted crimson bag.\n"
                + "pale salmon bags contain 4 vibrant aqua bags, 2 wavy blue bags, 5 striped violet bags.\n"
                + "pale gold bags contain 1 striped coral bag.\n"
                + "bright plum bags contain 5 faded aqua bags.\n"
                + "pale red bags contain 5 dotted silver bags, 3 clear chartreuse bags, 4 vibrant salmon bags.\n"
                + "striped tan bags contain 1 drab crimson bag.\n"
                + "mirrored red bags contain 3 striped gold bags, 1 mirrored gray bag.\n"
                + "bright turquoise bags contain 2 plaid blue bags, 4 clear tomato bags, 1 drab yellow bag, 5 vibrant black bags.\n"
                + "dark maroon bags contain 5 shiny magenta bags, 5 dotted fuchsia bags, 5 dull brown bags, 5 posh violet bags.\n"
                + "plaid chartreuse bags contain 5 drab gold bags, 1 vibrant white bag, 3 muted coral bags, 2 clear plum bags.\n"
                + "posh black bags contain 5 shiny brown bags, 5 posh white bags, 4 dim gray bags.\n"
                + "dotted teal bags contain 1 plaid bronze bag, 2 light violet bags, 1 muted beige bag.\n"
                + "plaid lime bags contain 4 mirrored black bags, 4 muted plum bags, 2 shiny maroon bags, 5 dim beige bags.\n"
                + "dim teal bags contain 2 muted coral bags.\n"
                + "vibrant aqua bags contain no other bags.\n"
                + "dotted turquoise bags contain 3 posh violet bags.\n"
                + "vibrant lime bags contain 5 dark bronze bags, 3 vibrant maroon bags, 5 mirrored cyan bags.\n"
                + "shiny gray bags contain 3 muted coral bags, 2 bright coral bags.\n"
                + "clear white bags contain 1 dim purple bag.\n"
                + "shiny salmon bags contain 5 dull tan bags, 1 posh violet bag, 4 mirrored magenta bags, 5 plaid tan bags.\n"
                + "dark gold bags contain 5 mirrored gray bags, 4 vibrant coral bags.\n"
                + "drab salmon bags contain 1 dull indigo bag.\n"
                + "faded salmon bags contain 2 bright blue bags.\n"
                + "vibrant salmon bags contain 4 muted purple bags, 4 striped plum bags.\n"
                + "dull red bags contain 2 pale white bags.\n"
                + "muted yellow bags contain 3 pale beige bags, 2 dim indigo bags.\n"
                + "bright beige bags contain 1 muted lavender bag, 1 dotted silver bag, 1 shiny bronze bag.\n"
                + "dull gold bags contain 4 posh gold bags.\n"
                + "striped crimson bags contain 5 dull blue bags, 4 bright gold bags, 2 shiny lavender bags.\n"
                + "drab maroon bags contain 1 wavy fuchsia bag.\n"
                + "wavy plum bags contain 4 posh tan bags, 1 muted maroon bag.\n"
                + "bright black bags contain 4 dark white bags, 5 dull maroon bags.\n"
                + "plaid aqua bags contain 3 wavy gray bags, 4 shiny blue bags.\n"
                + "wavy silver bags contain 1 bright tomato bag.\n"
                + "clear orange bags contain 1 dark brown bag, 3 wavy bronze bags, 5 bright tomato bags, 2 faded olive bags.\n"
                + "shiny lavender bags contain 4 dim purple bags.\n"
                + "dull crimson bags contain 5 bright plum bags, 1 pale yellow bag.\n"
                + "vibrant brown bags contain 2 dull tan bags, 1 pale yellow bag, 5 striped orange bags.\n"
                + "striped white bags contain 5 pale orange bags.\n"
                + "light blue bags contain 1 vibrant red bag, 3 bright cyan bags, 5 vibrant brown bags, 5 dim beige bags.\n"
                + "dark green bags contain 4 dotted black bags.\n"
                + "plaid black bags contain 5 dotted chartreuse bags, 1 wavy yellow bag, 4 faded cyan bags, 5 posh orange bags.\n"
                + "shiny turquoise bags contain 5 vibrant tan bags, 1 vibrant salmon bag, 1 muted olive bag.\n"
                + "clear silver bags contain 3 drab crimson bags, 3 bright magenta bags, 5 shiny blue bags, 4 drab lavender bags.\n"
                + "muted chartreuse bags contain 2 mirrored tan bags.\n"
                + "mirrored brown bags contain 5 clear yellow bags, 3 clear violet bags, 1 wavy plum bag.\n"
                + "dull white bags contain 5 shiny blue bags, 2 plaid tan bags, 3 vibrant silver bags, 4 pale orange bags.\n"
                + "clear lavender bags contain 2 posh bronze bags.\n"
                + "light gold bags contain 3 striped cyan bags, 5 dark lime bags.\n"
                + "plaid coral bags contain 1 posh salmon bag, 1 striped purple bag, 4 bright blue bags.\n"
                + "faded magenta bags contain 1 posh yellow bag, 2 bright plum bags.\n"
                + "faded maroon bags contain 2 plaid gray bags.\n"
                + "clear green bags contain 5 vibrant silver bags, 4 shiny gold bags.\n"
                + "mirrored tan bags contain 2 plaid purple bags, 4 dim purple bags, 5 vibrant crimson bags.\n"
                + "striped red bags contain 2 clear salmon bags.\n"
                + "dull aqua bags contain 1 plaid red bag, 3 vibrant aqua bags.\n"
                + "bright coral bags contain 4 muted fuchsia bags, 4 wavy beige bags.\n"
                + "wavy black bags contain 3 drab crimson bags, 3 vibrant white bags, 4 vibrant aqua bags.\n"
                + "dim white bags contain 1 dull olive bag, 5 vibrant white bags.\n"
                + "striped turquoise bags contain 2 drab turquoise bags.\n"
                + "shiny gold bags contain 2 mirrored blue bags, 1 muted brown bag, 3 dim purple bags.\n"
                + "bright gray bags contain 1 faded cyan bag, 3 dark plum bags, 1 light violet bag.\n"
                + "mirrored olive bags contain 5 vibrant gray bags, 1 plaid blue bag, 5 clear black bags, 2 dotted black bags.\n"
                + "posh red bags contain 5 muted olive bags, 2 dotted coral bags, 1 striped crimson bag.\n"
                + "clear teal bags contain 4 bright gold bags, 5 striped gray bags, 2 mirrored lime bags, 4 wavy indigo bags.\n"
                + "faded lime bags contain 4 plaid beige bags.\n"
                + "dull yellow bags contain 1 clear indigo bag, 1 drab beige bag, 2 plaid bronze bags.\n"
                + "muted beige bags contain no other bags.\n"
                + "wavy orange bags contain 3 shiny lime bags, 4 striped gold bags.\n"
                + "drab brown bags contain 1 bright red bag, 1 posh yellow bag, 3 dotted gray bags, 2 plaid green bags.\n"
                + "muted olive bags contain 4 posh maroon bags, 4 bright maroon bags, 3 faded olive bags.\n"
                + "dotted cyan bags contain 5 dotted purple bags, 5 pale olive bags, 5 dull plum bags.\n"
                + "vibrant olive bags contain 2 light violet bags, 2 dim violet bags, 4 mirrored black bags.\n"
                + "pale lime bags contain 4 dark purple bags, 1 shiny chartreuse bag.\n"
                + "dull purple bags contain 1 faded blue bag, 4 dull violet bags, 2 dim bronze bags, 2 vibrant crimson bags.\n"
                + "dotted red bags contain 4 bright magenta bags, 1 mirrored cyan bag, 1 wavy green bag, 4 dotted cyan bags.\n"
                + "vibrant silver bags contain 4 faded purple bags, 3 shiny yellow bags, 4 mirrored tan bags.\n"
                + "dark fuchsia bags contain 3 dark cyan bags.\n"
                + "muted crimson bags contain 3 bright tomato bags, 4 dark gold bags.\n"
                + "dark coral bags contain 3 faded magenta bags.\n"
                + "dull teal bags contain 3 drab turquoise bags, 5 dim salmon bags, 2 striped coral bags.\n"
                + "light brown bags contain 5 bright tomato bags, 4 mirrored salmon bags, 2 vibrant violet bags, 5 dark bronze bags.\n"
                + "bright brown bags contain 3 muted purple bags, 2 vibrant yellow bags, 3 pale fuchsia bags, 3 posh violet bags.\n"
                + "faded bronze bags contain 2 bright bronze bags, 2 dim tomato bags, 3 mirrored beige bags.\n"
                + "dim indigo bags contain 2 vibrant gold bags.\n"
                + "drab cyan bags contain 5 muted orange bags, 4 dotted orange bags, 3 striped tan bags, 5 dull turquoise bags.\n"
                + "mirrored plum bags contain 1 dotted black bag, 2 faded silver bags, 1 plaid red bag.\n"
                + "dull maroon bags contain 5 dark violet bags, 2 bright brown bags, 4 clear blue bags.\n"
                + "light silver bags contain 3 bright blue bags, 1 muted brown bag.\n"
                + "dim blue bags contain 5 dim purple bags, 5 pale orange bags.\n"
                + "clear blue bags contain 2 plaid tan bags, 3 muted chartreuse bags, 2 faded lavender bags.\n"
                + "mirrored salmon bags contain 2 striped coral bags, 2 plaid purple bags.\n"
                + "faded violet bags contain 3 clear gold bags, 2 posh white bags.\n"
                + "light beige bags contain 5 vibrant tan bags, 4 muted lavender bags, 3 plaid bronze bags.\n"
                + "shiny black bags contain 3 vibrant violet bags, 1 wavy brown bag.\n"
                + "dotted plum bags contain 4 faded yellow bags, 5 light lavender bags.\n"
                + "vibrant chartreuse bags contain 1 mirrored fuchsia bag.\n"
                + "striped green bags contain 2 wavy lime bags, 5 mirrored turquoise bags, 2 muted aqua bags, 3 wavy gold bags.\n"
                + "plaid plum bags contain 5 plaid tan bags, 2 pale gold bags, 5 mirrored salmon bags.\n"
                + "dark chartreuse bags contain 1 bright orange bag, 5 bright lavender bags, 2 light black bags.\n"
                + "muted indigo bags contain 2 posh fuchsia bags.\n"
                + "posh tan bags contain 3 dull silver bags, 2 clear tan bags, 4 drab beige bags.\n"
                + "shiny brown bags contain 5 shiny gold bags.\n"
                + "pale orange bags contain 2 striped gray bags, 5 clear beige bags.\n"
                + "pale lavender bags contain 1 shiny lime bag, 1 bright cyan bag.\n"
                + "pale bronze bags contain 2 faded blue bags, 4 pale yellow bags, 5 shiny red bags.\n"
                + "muted bronze bags contain 3 light beige bags, 4 muted fuchsia bags, 5 striped chartreuse bags.\n"
                + "light crimson bags contain 2 faded coral bags.\n"
                + "drab coral bags contain 4 faded black bags, 4 drab white bags, 5 wavy maroon bags, 4 muted violet bags.\n"
                + "vibrant lavender bags contain 2 striped crimson bags.\n"
                + "posh magenta bags contain 1 bright chartreuse bag, 3 drab white bags, 4 dull violet bags.\n"
                + "dim maroon bags contain 1 drab lime bag, 4 faded aqua bags, 5 dark lavender bags.\n"
                + "clear purple bags contain 1 pale lavender bag.\n"
                + "dim magenta bags contain 3 dull violet bags, 4 pale red bags.\n"
                + "plaid red bags contain 5 clear indigo bags.\n"
                + "light gray bags contain 2 dark white bags, 5 posh green bags, 1 wavy silver bag.\n"
                + "plaid beige bags contain 2 dotted brown bags, 2 clear white bags.\n"
                + "faded gold bags contain 2 clear white bags, 1 muted purple bag, 1 striped plum bag.\n"
                + "drab yellow bags contain 3 striped lime bags, 5 muted fuchsia bags, 1 wavy black bag, 3 pale white bags.\n"
                + "dark indigo bags contain 4 striped indigo bags, 4 mirrored violet bags, 3 muted brown bags.\n"
                + "muted black bags contain 1 plaid tan bag, 2 bright tomato bags.\n"
                + "shiny beige bags contain 5 dark bronze bags.\n"
                + "bright cyan bags contain 2 dark lavender bags, 5 striped plum bags, 3 mirrored tan bags, 5 plaid teal bags.\n"
                + "dotted gold bags contain 2 pale gold bags, 1 drab silver bag.\n"
                + "wavy tomato bags contain 4 dotted crimson bags, 4 mirrored lime bags, 2 dim indigo bags.\n"
                + "muted aqua bags contain 3 muted beige bags.\n"
                + "plaid white bags contain 2 bright green bags, 3 mirrored blue bags, 3 dull maroon bags, 2 dotted chartreuse bags.\n"
                + "plaid teal bags contain 1 plaid tan bag, 3 wavy beige bags.\n"
                + "light salmon bags contain 5 faded turquoise bags, 5 muted green bags, 2 plaid bronze bags, 3 plaid indigo bags.\n"
                + "dark aqua bags contain 2 wavy plum bags, 2 dotted red bags, 2 light red bags.\n"
                + "pale aqua bags contain 4 light aqua bags, 4 clear cyan bags, 5 dull tan bags, 5 bright olive bags.\n"
                + "posh green bags contain 5 pale blue bags.\n"
                + "faded chartreuse bags contain 2 shiny red bags.\n"
                + "pale purple bags contain 2 mirrored cyan bags.\n"
                + "striped magenta bags contain 1 muted aqua bag, 1 plaid turquoise bag, 5 dim purple bags, 3 wavy red bags.\n"
                + "plaid crimson bags contain 5 muted brown bags, 5 mirrored tomato bags.\n"
                + "plaid orange bags contain 1 dotted salmon bag, 2 pale aqua bags, 4 shiny tomato bags, 1 dull salmon bag.\n"
                + "faded red bags contain 1 clear tan bag.\n"
                + "plaid fuchsia bags contain 1 dark black bag, 1 dotted teal bag, 2 dark aqua bags, 2 dull bronze bags.\n"
                + "pale crimson bags contain 5 dull brown bags, 3 vibrant coral bags.\n"
                + "muted lavender bags contain 2 posh silver bags, 1 plaid cyan bag.\n"
                + "dull violet bags contain 5 posh coral bags, 5 shiny red bags, 5 drab gold bags, 4 posh white bags.\n"
                + "dull coral bags contain 5 bright lime bags.\n"
                + "posh gold bags contain 1 vibrant violet bag, 1 muted lavender bag.\n"
                + "drab lime bags contain 4 shiny salmon bags, 1 plaid plum bag, 1 wavy tomato bag, 1 wavy red bag.\n"
                + "plaid tan bags contain 3 muted purple bags.\n"
                + "posh chartreuse bags contain 5 clear white bags, 2 dotted violet bags, 5 light teal bags, 5 vibrant gold bags.\n"
                + "faded yellow bags contain 1 muted coral bag, 3 shiny yellow bags, 4 shiny lime bags.\n"
                + "vibrant cyan bags contain 3 muted purple bags, 4 pale tomato bags, 4 vibrant beige bags, 2 muted black bags.\n"
                + "plaid tomato bags contain 3 faded fuchsia bags.\n"
                + "dotted maroon bags contain 4 dull tan bags, 4 plaid cyan bags, 5 bright gold bags, 4 drab blue bags.\n"
                + "drab gray bags contain 4 faded olive bags, 3 vibrant crimson bags.\n"
                + "wavy maroon bags contain 1 wavy red bag, 4 posh white bags, 4 wavy tomato bags.\n"
                + "dull lavender bags contain 2 dim salmon bags, 3 dotted aqua bags, 2 dim turquoise bags, 4 muted gold bags.\n"
                + "dim chartreuse bags contain 4 muted yellow bags, 1 muted violet bag, 2 shiny orange bags, 4 drab salmon bags.\n"
                + "bright red bags contain 1 dull red bag, 1 muted fuchsia bag.\n"
                + "clear yellow bags contain 2 dim violet bags, 5 dim tomato bags, 4 pale indigo bags.\n"
                + "wavy aqua bags contain 5 shiny red bags, 1 pale gold bag, 2 mirrored blue bags, 4 dull violet bags.\n"
                + "bright lime bags contain 5 posh tomato bags, 2 faded fuchsia bags, 4 posh yellow bags, 5 dull brown bags.\n"
                + "bright chartreuse bags contain 2 posh fuchsia bags, 1 posh yellow bag, 3 dotted chartreuse bags.\n"
                + "mirrored magenta bags contain 1 shiny teal bag, 1 mirrored maroon bag, 3 drab turquoise bags.\n"
                + "pale yellow bags contain 3 plaid purple bags, 2 vibrant black bags.\n"
                + "dark teal bags contain 4 clear salmon bags, 3 mirrored blue bags, 3 pale blue bags.\n"
                + "clear coral bags contain 2 dark indigo bags, 5 dark plum bags, 5 plaid beige bags.\n"
                + "muted brown bags contain no other bags.\n"
                + "dotted purple bags contain 1 posh bronze bag, 1 vibrant chartreuse bag, 5 striped indigo bags.\n"
                + "plaid violet bags contain 2 posh white bags.\n"
                + "dull turquoise bags contain 1 drab red bag, 5 muted aqua bags, 4 drab violet bags, 2 muted purple bags.\n"
                + "light coral bags contain 3 posh bronze bags, 5 vibrant silver bags.\n"
                + "striped lime bags contain 5 muted olive bags.\n"
                + "pale cyan bags contain 2 mirrored tomato bags, 3 dull red bags, 4 striped indigo bags, 2 dark maroon bags.\n"
                + "muted tomato bags contain 2 posh tomato bags, 3 dim teal bags, 4 drab indigo bags.\n"
                + "shiny coral bags contain 4 mirrored beige bags, 1 muted magenta bag, 2 light green bags, 3 mirrored olive bags.\n"
                + "vibrant black bags contain 2 dotted black bags, 4 dull red bags, 2 light lavender bags.\n"
                + "vibrant green bags contain 5 mirrored bronze bags, 5 dotted teal bags, 5 plaid tomato bags, 2 muted purple bags.\n"
                + "clear aqua bags contain 2 plaid teal bags, 3 posh tomato bags, 3 light bronze bags, 3 posh teal bags.\n"
                + "dotted brown bags contain 5 pale white bags, 2 dim indigo bags, 1 shiny yellow bag, 3 plaid gray bags.\n"
                + "striped beige bags contain 3 striped indigo bags, 4 faded lavender bags, 1 drab crimson bag, 1 vibrant tomato bag.\n"
                + "plaid cyan bags contain 4 shiny gold bags, 1 wavy beige bag.\n"
                + "mirrored gold bags contain 3 vibrant coral bags.\n"
                + "plaid turquoise bags contain 5 striped coral bags.\n"
                + "pale magenta bags contain 1 drab tomato bag, 4 dark chartreuse bags, 4 striped tan bags, 5 vibrant white bags.\n"
                + "pale green bags contain 4 shiny tan bags.\n"
                + "faded indigo bags contain 3 bright plum bags, 3 posh teal bags.\n"
                + "dim red bags contain 2 striped silver bags, 4 dim blue bags.\n"
                + "bright tan bags contain 1 vibrant cyan bag, 5 mirrored magenta bags.\n"
                + "dotted violet bags contain 1 bright bronze bag, 4 dotted silver bags, 1 drab silver bag, 4 plaid indigo bags.\n"
                + "dim black bags contain 1 dark magenta bag, 4 vibrant tan bags, 5 light magenta bags.\n"
                + "bright aqua bags contain 2 muted gold bags, 3 dotted gray bags.\n"
                + "plaid salmon bags contain 2 vibrant gold bags, 2 bright maroon bags, 2 shiny lime bags, 2 mirrored salmon bags.\n"
                + "drab chartreuse bags contain 3 shiny crimson bags.\n"
                + "shiny magenta bags contain 2 striped plum bags.\n"
                + "dotted blue bags contain 2 muted salmon bags.\n"
                + "bright white bags contain 2 pale olive bags, 2 dotted black bags.\n"
                + "clear red bags contain 2 bright chartreuse bags, 5 striped magenta bags.\n"
                + "mirrored chartreuse bags contain 2 vibrant crimson bags, 2 drab blue bags.\n"
                + "striped fuchsia bags contain 2 muted salmon bags, 2 posh bronze bags.\n"
                + "posh blue bags contain 2 faded bronze bags, 4 striped purple bags.\n"
                + "mirrored fuchsia bags contain 5 mirrored tan bags, 4 muted coral bags.\n"
                + "posh beige bags contain 5 drab violet bags.\n"
                + "striped violet bags contain 2 wavy plum bags, 1 pale crimson bag.\n"
                + "vibrant turquoise bags contain 4 plaid gray bags.\n"
                + "dotted bronze bags contain 2 drab maroon bags, 4 posh plum bags, 2 dotted brown bags, 5 mirrored cyan bags.\n"
                + "dim cyan bags contain 2 pale orange bags, 2 posh white bags, 3 plaid salmon bags.\n"
                + "vibrant gold bags contain 1 bright coral bag, 2 mirrored black bags.\n"
                + "posh bronze bags contain 3 bright green bags, 5 faded turquoise bags, 5 plaid plum bags, 3 dull tan bags.\n"
                + "pale chartreuse bags contain 3 vibrant gray bags, 5 posh coral bags, 5 bright white bags, 4 faded white bags.\n"
                + "drab crimson bags contain 2 wavy beige bags, 3 striped coral bags, 1 dim purple bag, 3 pale gold bags.\n"
                + "mirrored lime bags contain 5 striped coral bags, 2 wavy beige bags.\n"
                + "shiny green bags contain 4 plaid silver bags, 2 dim teal bags, 2 dotted teal bags, 2 drab turquoise bags.\n"
                + "light tomato bags contain 4 dark gold bags.\n"
                + "mirrored beige bags contain 5 posh gray bags, 5 dull olive bags, 3 drab crimson bags, 4 striped silver bags.\n"
                + "vibrant indigo bags contain 2 pale brown bags, 2 vibrant tomato bags, 3 dim violet bags.\n"
                + "dim plum bags contain 1 plaid aqua bag, 1 wavy plum bag, 1 wavy aqua bag.\n"
                + "light indigo bags contain 4 mirrored purple bags.\n"
                + "faded brown bags contain 2 dim gold bags.\n"
                + "dim gold bags contain 4 dotted purple bags, 5 dotted black bags, 4 vibrant beige bags, 4 clear magenta bags.\n"
                + "clear cyan bags contain 1 mirrored blue bag, 5 clear gray bags.\n"
                + "dark yellow bags contain 3 dull violet bags, 3 dotted crimson bags, 1 dark bronze bag, 3 vibrant tomato bags.\n"
                + "plaid silver bags contain 5 drab gray bags.\n"
                + "vibrant yellow bags contain 5 plaid teal bags, 1 shiny silver bag, 1 mirrored black bag.\n"
                + "dull olive bags contain 1 dark bronze bag, 5 wavy green bags, 2 muted cyan bags.\n"
                + "plaid brown bags contain 3 drab indigo bags.\n"
                + "faded cyan bags contain 3 light lavender bags.\n"
                + "drab orange bags contain 5 plaid teal bags, 1 clear fuchsia bag.\n"
                + "muted tan bags contain 4 faded bronze bags, 4 vibrant green bags.\n"
                + "dull cyan bags contain 5 striped maroon bags, 2 dim plum bags.\n"
                + "wavy red bags contain 3 mirrored fuchsia bags, 5 vibrant salmon bags.\n"
                + "wavy lime bags contain 5 faded lavender bags, 1 posh maroon bag.\n"
                + "dotted tan bags contain 2 shiny teal bags, 2 plaid gray bags, 2 pale silver bags, 3 dim violet bags.\n"
                + "clear salmon bags contain 4 striped white bags, 3 light coral bags, 1 mirrored white bag, 5 dotted silver bags.\n"
                + "dark purple bags contain 1 shiny lime bag, 3 dull salmon bags.\n"
                + "dim purple bags contain 5 wavy beige bags, 5 vibrant aqua bags, 5 muted purple bags.\n"
                + "striped gray bags contain 5 muted lavender bags, 1 clear blue bag.\n"
                + "bright yellow bags contain 4 bright fuchsia bags, 3 drab brown bags, 5 shiny lime bags.\n"
                + "light teal bags contain 5 faded olive bags.\n"
                + "wavy yellow bags contain 2 striped cyan bags, 5 dim indigo bags.\n"
                + "vibrant tomato bags contain 2 shiny violet bags, 2 mirrored blue bags, 1 pale violet bag, 2 faded olive bags.\n"
                + "pale silver bags contain 2 dotted magenta bags, 2 mirrored salmon bags, 2 dim blue bags.\n"
                + "mirrored lavender bags contain 3 pale teal bags, 2 posh gray bags.\n"
                + "striped chartreuse bags contain 3 plaid bronze bags.\n"
                + "dotted chartreuse bags contain 1 pale white bag, 1 striped tan bag, 1 striped beige bag, 1 dull brown bag.\n"
                + "muted silver bags contain 2 shiny tan bags, 5 mirrored red bags, 3 drab brown bags.\n"
                + "clear maroon bags contain 1 shiny gray bag, 4 posh purple bags, 5 pale silver bags.\n"
                + "light cyan bags contain 3 vibrant yellow bags.\n"
                + "plaid magenta bags contain 3 bright olive bags, 2 faded violet bags, 1 bright salmon bag.\n"
                + "drab gold bags contain 1 dull blue bag, 5 mirrored gold bags, 3 striped cyan bags, 3 mirrored cyan bags.\n"
                + "light green bags contain 3 dotted brown bags.\n"
                + "dim silver bags contain 2 pale cyan bags, 3 muted gold bags, 2 faded fuchsia bags.\n"
                + "faded black bags contain 5 dim orange bags, 2 shiny green bags, 2 faded cyan bags, 3 dull yellow bags.\n"
                + "bright bronze bags contain 5 plaid indigo bags.\n"
                + "light orange bags contain 4 wavy beige bags, 5 mirrored blue bags, 5 faded turquoise bags.\n"
                + "dark black bags contain 1 posh maroon bag, 1 faded turquoise bag, 2 drab violet bags, 4 mirrored white bags.\n"
                + "dark gray bags contain 3 dotted coral bags, 3 plaid bronze bags.\n"
                + "shiny aqua bags contain 1 muted coral bag.\n"
                + "striped aqua bags contain 2 posh bronze bags.\n"
                + "dull plum bags contain 4 drab gray bags, 5 posh maroon bags.\n"
                + "posh salmon bags contain 2 mirrored bronze bags, 5 plaid aqua bags.\n"
                + "muted blue bags contain 1 drab yellow bag.\n"
                + "dim lime bags contain 4 plaid teal bags, 5 dotted orange bags, 5 wavy silver bags, 3 muted purple bags.\n"
                + "striped cyan bags contain 1 mirrored chartreuse bag.\n"
                + "dull beige bags contain 3 drab red bags, 4 vibrant olive bags.\n"
                + "wavy indigo bags contain 4 pale orange bags, 1 vibrant salmon bag, 5 wavy red bags, 2 plaid indigo bags.\n"
                + "drab tomato bags contain 3 clear gold bags.\n"
                + "shiny crimson bags contain 2 vibrant lime bags, 5 shiny lavender bags, 3 dark purple bags, 3 light beige bags.\n"
                + "bright magenta bags contain 4 striped gray bags, 5 dim cyan bags.\n"
                + "plaid maroon bags contain 1 bright magenta bag, 2 dark olive bags.\n"
                + "faded white bags contain 2 faded turquoise bags.\n"
                + "pale plum bags contain 3 clear beige bags, 1 mirrored violet bag.\n"
                + "dim fuchsia bags contain 1 posh maroon bag, 1 dull tan bag.\n"
                + "dark olive bags contain 4 clear chartreuse bags, 5 light cyan bags, 5 striped magenta bags.\n"
                + "dull lime bags contain 1 striped lavender bag, 1 shiny lavender bag, 2 faded cyan bags.\n"
                + "faded fuchsia bags contain 4 wavy aqua bags, 3 dark brown bags, 1 pale orange bag, 3 striped indigo bags.\n"
                + "posh olive bags contain 3 drab maroon bags, 1 vibrant white bag, 2 wavy lime bags, 5 drab purple bags.\n"
                + "dull black bags contain 4 posh tomato bags, 4 wavy aqua bags, 2 dull tomato bags, 2 clear orange bags.\n"
                + "striped blue bags contain 5 pale crimson bags, 5 clear chartreuse bags.\n"
                + "shiny blue bags contain 1 plaid tan bag, 1 plaid silver bag.\n"
                + "drab bronze bags contain 5 faded fuchsia bags.\n"
                + "posh aqua bags contain 3 dull turquoise bags, 5 dim olive bags.\n"
                + "plaid lavender bags contain 5 mirrored red bags, 1 striped salmon bag, 2 mirrored turquoise bags, 4 dotted cyan bags.\n"
                + "shiny purple bags contain 1 vibrant coral bag, 1 striped blue bag.\n"
                + "mirrored purple bags contain 3 plaid teal bags.\n"
                + "vibrant coral bags contain 1 striped coral bag, 4 pale gold bags.\n"
                + "drab blue bags contain 4 drab gray bags, 4 vibrant coral bags, 1 plaid teal bag.\n"
                + "mirrored green bags contain 2 dull brown bags, 1 faded white bag.\n"
                + "dim beige bags contain 3 clear blue bags, 1 shiny magenta bag.\n"
                + "striped tomato bags contain 4 vibrant silver bags, 2 bright yellow bags.\n"
                + "clear bronze bags contain 5 striped coral bags, 3 wavy green bags, 1 bright violet bag.\n"
                + "shiny teal bags contain 1 drab white bag.\n"
                + "faded lavender bags contain 5 dim teal bags, 2 faded olive bags, 2 dim purple bags, 2 pale gold bags.\n"
                + "posh gray bags contain 2 mirrored tan bags.\n"
                + "pale brown bags contain 5 dull tan bags, 2 posh tomato bags.\n"
                + "shiny plum bags contain 2 mirrored blue bags, 5 dark cyan bags, 2 dark teal bags.\n"
                + "wavy lavender bags contain 1 wavy gold bag, 2 wavy maroon bags, 2 dark black bags.\n"
                + "shiny tan bags contain 3 bright bronze bags, 1 posh fuchsia bag, 1 dark maroon bag, 4 wavy salmon bags.\n"
                + "dim coral bags contain 3 faded indigo bags, 5 clear white bags.\n"
                + "mirrored turquoise bags contain 4 vibrant coral bags, 4 pale gold bags, 1 clear blue bag.\n"
                + "muted coral bags contain no other bags.\n"
                + "drab plum bags contain 4 drab gray bags, 4 dotted green bags, 2 bright gray bags.\n"
                + "muted gold bags contain 3 shiny red bags, 5 light white bags, 3 mirrored maroon bags.\n"
                + "light violet bags contain 1 plaid tan bag, 2 plaid turquoise bags.\n"
                + "dotted coral bags contain 4 dark crimson bags, 3 muted plum bags, 2 vibrant black bags, 4 drab gray bags.\n"
                + "pale fuchsia bags contain 3 dark brown bags.\n"
                + "dark turquoise bags contain 3 plaid teal bags, 5 dull orange bags.\n"
                + "dark blue bags contain 4 drab silver bags, 2 shiny brown bags.\n"
                + "muted green bags contain 1 mirrored violet bag, 3 posh silver bags, 2 bright coral bags, 4 clear chartreuse bags.\n"
                + "posh brown bags contain 2 mirrored turquoise bags.\n"
                + "vibrant tan bags contain 3 drab gray bags.\n"
                + "dull indigo bags contain 1 dim tomato bag, 3 pale brown bags.\n"
                + "pale teal bags contain 3 light beige bags, 1 plaid indigo bag, 3 striped tan bags, 5 vibrant white bags.\n"
                + "striped purple bags contain 2 drab white bags.\n"
                + "pale coral bags contain 3 plaid teal bags.\n"
                + "clear gold bags contain 1 muted purple bag, 4 muted coral bags.\n"
                + "faded teal bags contain 1 pale tan bag, 4 dark indigo bags, 1 posh olive bag.\n"
                + "dotted orange bags contain 5 shiny brown bags, 3 striped plum bags, 3 plaid silver bags.\n"
                + "plaid olive bags contain 1 posh white bag, 2 striped bronze bags, 2 dark gold bags, 3 plaid teal bags.\n"
                + "dark lime bags contain 4 mirrored gray bags, 2 pale aqua bags.\n"
                + "mirrored maroon bags contain 5 muted beige bags.\n"
                + "shiny red bags contain 5 posh silver bags, 5 shiny blue bags.\n"
                + "drab magenta bags contain 4 muted plum bags, 4 light yellow bags.\n"
                + "plaid purple bags contain no other bags.\n"
                + "drab indigo bags contain 1 dull blue bag, 3 wavy maroon bags, 5 pale gold bags, 3 pale crimson bags.\n"
                + "vibrant white bags contain 1 dim salmon bag.\n"
                + "mirrored teal bags contain 4 dotted chartreuse bags, 4 dim brown bags, 5 striped yellow bags.\n"
                + "plaid gold bags contain 2 posh crimson bags, 5 muted green bags, 5 muted salmon bags, 1 pale plum bag.\n"
                + "striped indigo bags contain 2 muted beige bags, 4 mirrored fuchsia bags.\n"
                + "bright purple bags contain 4 dim violet bags.\n"
                + "dark salmon bags contain 2 clear silver bags, 5 wavy fuchsia bags, 5 bright salmon bags.\n"
                + "muted magenta bags contain 5 bright bronze bags, 1 dark red bag, 4 faded fuchsia bags.\n"
                + "drab olive bags contain 1 dim gold bag, 5 clear gold bags, 4 muted white bags.\n"
                + "mirrored black bags contain 4 dim teal bags.\n"
                + "dull bronze bags contain 3 dull white bags, 1 striped yellow bag, 1 striped crimson bag, 1 pale teal bag.\n"
                + "dotted black bags contain 3 faded purple bags, 3 vibrant coral bags, 2 posh silver bags, 5 vibrant aqua bags.\n"
                + "drab aqua bags contain 1 striped lavender bag, 5 shiny lavender bags.\n"
                + "shiny maroon bags contain 5 posh crimson bags, 4 drab blue bags, 1 pale black bag.\n"
                + "faded plum bags contain 2 posh tomato bags, 1 vibrant fuchsia bag, 2 faded black bags.\n"
                + "wavy coral bags contain 5 shiny gold bags.\n"
                + "dull brown bags contain 4 mirrored tan bags.\n"
                + "pale gray bags contain 5 dim maroon bags.\n"
                + "dim tan bags contain 5 clear blue bags, 1 wavy bronze bag.\n"
                + "plaid bronze bags contain 4 bright coral bags, 1 dotted crimson bag, 1 mirrored black bag.";

        return Arrays.stream(inputStr.split("\\n"))
                .filter(s -> !s.contains("no other bags"))
                .map(OuterBag::new);
    }

    public static class OuterBag {

        public final Bag input;
        public final Bag[] output;

        public OuterBag(String trade) {
            String[] inputOutput = trade.split(" contain ");
            output = stream(inputOutput[1].split(", ")).map(Bag::new).toArray(Bag[]::new);
            input = new Bag(1, inputOutput[0].replace(" bags", ""));
        }
    }

    public static class Bag {

        public long amount;
        public final String item;

        public Bag(String item) {
            amount = Integer.parseInt(item.substring(0, 1));
            this.item = item.substring(2).replaceAll(" bags?\\.?", "");
        }

        public Bag(long i, String string) {
            amount = i;
            item = string;
        }
    }
}
